name: CI multiplataforma
on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Instala Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - run: npm install
      - run: npm test
